<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name . ' - Terms of Sale';
$this->breadcrumbs=array(
	'Terms of Sale',
);
?>
<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/courtesyMenu.css" />

<h3>Terms of Sale</h3>
<div id="termsContent">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In orci lorem, porta ac rutrum eu, cursus ac purus. Vivamus iaculis porttitor odio sit amet commodo. Fusce tempor tincidunt diam, in posuere orci ullamcorper quis. Nullam tempor auctor mi a rutrum. Nulla elit eros, consequat et convallis a, adipiscing vitae nulla. Aliquam erat volutpat. Vestibulum enim leo, elementum et sollicitudin ac, congue at lacus. Vivamus elit magna, mollis at semper a, volutpat a nisl. Nam ante velit, vehicula in dignissim in, mattis et enim. Mauris velit erat, malesuada quis elementum ac, vestibulum nec arcu. Phasellus viverra luctus venenatis. Phasellus vitae nunc massa, vitae pellentesque magna. Vestibulum erat nisi, iaculis id sollicitudin id, luctus sit amet leo. Vivamus elit dolor, fermentum sit amet pellentesque ut, vestibulum eget diam. Pellentesque ipsum velit, blandit non ultrices nec, ullamcorper vitae mi.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In orci lorem, porta ac rutrum eu, cursus ac purus. Vivamus iaculis porttitor odio sit amet commodo. Fusce tempor tincidunt diam, in posuere orci ullamcorper quis. Nullam tempor auctor mi a rutrum. Nulla elit eros, consequat et convallis a, adipiscing vitae nulla. Aliquam erat volutpat. Vestibulum enim leo, elementum et sollicitudin ac, congue at lacus. Vivamus elit magna, mollis at semper a, volutpat a nisl. Nam ante velit, vehicula in dignissim in, mattis et enim. Mauris velit erat, malesuada quis elementum ac, vestibulum nec arcu. Phasellus viverra luctus venenatis. Phasellus vitae nunc massa, vitae pellentesque magna. Vestibulum erat nisi, iaculis id sollicitudin id, luctus sit amet leo. Vivamus elit dolor, fermentum sit amet pellentesque ut, vestibulum eget diam. Pellentesque ipsum velit, blandit non ultrices nec, ullamcorper vitae mi.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In orci lorem, porta ac rutrum eu, cursus ac purus. Vivamus iaculis porttitor odio sit amet commodo. Fusce tempor tincidunt diam, in posuere orci ullamcorper quis. Nullam tempor auctor mi a rutrum. Nulla elit eros, consequat et convallis a, adipiscing vitae nulla. Aliquam erat volutpat. Vestibulum enim leo, elementum et sollicitudin ac, congue at lacus. Vivamus elit magna, mollis at semper a, volutpat a nisl. Nam ante velit, vehicula in dignissim in, mattis et enim. Mauris velit erat, malesuada quis elementum ac, vestibulum nec arcu. Phasellus viverra luctus venenatis. Phasellus vitae nunc massa, vitae pellentesque magna. Vestibulum erat nisi, iaculis id sollicitudin id, luctus sit amet leo. Vivamus elit dolor, fermentum sit amet pellentesque ut, vestibulum eget diam. Pellentesque ipsum velit, blandit non ultrices nec, ullamcorper vitae mi.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In orci lorem, porta ac rutrum eu, cursus ac purus. Vivamus iaculis porttitor odio sit amet commodo. Fusce tempor tincidunt diam, in posuere orci ullamcorper quis. Nullam tempor auctor mi a rutrum. Nulla elit eros, consequat et convallis a, adipiscing vitae nulla. Aliquam erat volutpat. Vestibulum enim leo, elementum et sollicitudin ac, congue at lacus. Vivamus elit magna, mollis at semper a, volutpat a nisl. Nam ante velit, vehicula in dignissim in, mattis et enim. Mauris velit erat, malesuada quis elementum ac, vestibulum nec arcu. Phasellus viverra luctus venenatis. Phasellus vitae nunc massa, vitae pellentesque magna. Vestibulum erat nisi, iaculis id sollicitudin id, luctus sit amet leo. Vivamus elit dolor, fermentum sit amet pellentesque ut, vestibulum eget diam. Pellentesque ipsum velit, blandit non ultrices nec, ullamcorper vitae mi.
    </p>
</div>